site_name: AIAgents4Pharma

nav:
  - Home: index.md

  - Talk2Biomodels: 
      - Introduction: talk2biomodels/models/intro.md
      - Tutorials: ./notebooks/talk2biomodels/tutorial.ipynb
      - Models:
        - System Bio Model: talk2biomodels/models/sys_bio_model.md
        - Basico Model : talk2biomodels/models/basico_model.md 
      - Tools:
        - Search models: talk2biomodels/tools/search_models.md
        - Model description: talk2biomodels/tools/model_description.md
        - Fetch parameters: talk2biomodels/tools/fetch_parameters.md
        - Simulate model: talk2biomodels/tools/simulate_model.md
        - Ask questions: talk2biomodels/tools/ask_question.md
        - Custom figures: talk2biomodels/tools/custom_plotter.md
        
  - Talk2Cells:
      - Talk2Cells: talk2cells/intro.md

  - Talk2Knowledgegraphs :
      - Talk2Knowledgegraphs: Talk2KnowledgeGraphs/intro.md 

  - Documentation : 
    - Ops:
        - Introduction: ops/Documentation_intro.md
        - CodeOps : ops/CodeOps.md
        - DevOps : ops/DevOps.md
    - Contributing:
        - Contributing : CONTRIBUTING.md 

repo_url: https://github.com/VirtualPatientEngine/AIAgents4Pharma
repo_name: VPE/AIAgents4Pharma

extra_css:
  - VPE.png
theme:
  name: material
  logo: ./robot.png
  palette:
    - primary: teal
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.scrollable
plugins:
  - search:
      lang:
        - en
        - de
  - mkdocstrings:
      handlers:
        python:
          options:
            filters: None
  - mkdocs-jupyter:
      include_source: True
  - tags
  - include-markdown

markdown_extensions:
  - pymdownx.highlight
      # anchor_linenums: true
      # line_spans: __span
      # pygments_lang_class: true
  - pymdownx.superfences

extra:
  notebooks:
    - overview.md: notebooks/overview.md